require("user.pluginconf.cmp")
require("user.pluginconf.telescope")
require("user.pluginconf.treesitter")
require("user.pluginconf.autopairs")
require("user.pluginconf.comment")
require("user.pluginconf.gitsigns")
require("user.pluginconf.nvim-tree")
require("user.pluginconf.bufferline")
require("user.pluginconf.lualine")
require("user.pluginconf.toggleterm")
require("user.pluginconf.impatient")
require("user.pluginconf.illuminate")
require("user.pluginconf.indentline")
-- require("user.pluginconf.alpha")
require("user.pluginconf.null-ls")
-- mason order matters
require("user.pluginconf.mason")
require("user.pluginconf.mason-lspconfig")
-- end mason
require("user.pluginconf.cosmic-ui")
require("user.pluginconf.aerial")
require("user.pluginconf.editorconfig")
require("user.pluginconf.luasnip")
require("user.pluginconf.neoscroll")
require("user.pluginconf.marks")
require("user.pluginconf.colorizer")
require("user.pluginconf.treesitter-context")
require("user.pluginconf.renamer")
require("user.pluginconf.persisted")
require("user.pluginconf.nvim-spectre")
require("user.pluginconf.hop")
require("user.pluginconf.colorpicker")
-- require("user.pluginconf.session-manager")
require("user.pluginconf.scope")
-- require("user.pluginconf.copilot")
require("user.pluginconf.chatgpt")
require("user.pluginconf.peek")
require("user.pluginconf.mason-null-ls")
require("user.pluginconf.headlines")
require("user.pluginconf.jsonpath")
-- require("user.pluginconf.mason-null-ls")
require("user.pluginconf.wtf")
require("user.pluginconf.rest")
require("user.pluginconf.mini-ai")
require("user.pluginconf.noice")
require("user.pluginconf.render-markdown")
-- require("user.pluginconf.harpoon")
require("user.pluginconf.grapple")
