require("pluginconf.cmp")
require("pluginconf.telescope")
require("pluginconf.treesitter")
require("pluginconf.autopairs")
require("pluginconf.comment")
require("pluginconf.gitsigns")
require("pluginconf.nvim-tree")
require("pluginconf.bufferline")
require("pluginconf.lualine")
require("pluginconf.toggleterm")
require("pluginconf.impatient")
require("pluginconf.illuminate")
require("pluginconf.indentline")
-- require("pluginconf.alpha")
require("pluginconf.null-ls")
-- mason order matters
require("pluginconf.mason")
require("pluginconf.mason-lspconfig")
-- end mason
require("pluginconf.cosmic-ui")
require("pluginconf.aerial")
require("pluginconf.editorconfig")
require("pluginconf.luasnip")
require("pluginconf.neoscroll")
require("pluginconf.marks")
require("pluginconf.colorizer")
require("pluginconf.renamer")
require("pluginconf.persisted")
require("pluginconf.nvim-spectre")
require("pluginconf.hop")
require("pluginconf.colorpicker")
-- require("pluginconf.session-manager")
require("pluginconf.scope")
-- require("pluginconf.copilot")
require("pluginconf.peek")
require("pluginconf.mason-null-ls")
require("pluginconf.headlines")
require("pluginconf.jsonpath")
-- require("pluginconf.mason-null-ls")
require("pluginconf.wtf")
require("pluginconf.rest")
require("pluginconf.mini-ai")
require("pluginconf.noice")
require("pluginconf.pretty-ts-errors")
require("pluginconf.render-markdown")
require("pluginconf.ts-error-translator")
-- require("pluginconf.harpoon")
require("pluginconf.grapple")
require("pluginconf.dap")
require("pluginconf.smart-splits")
require("pluginconf.mason-dap")
require("pluginconf.dap-virtual-text")
