-- local on_attach = function(_, bufnr)
--   -- Enable completion triggered by <c-x><c-o>
--   vim.api.nvim_buf_set_option(bufnr, "omnifunc", "v:lua.vim.lsp.omnifunc")
-- end
--
-- require("lspconfig")["tsserver"].setup {
--   on_attach = on_attach,
-- }
