#!/bin/sh

Feat: Config nvim-cmp

Feat: Install this cool stuff https://github.com/hrsh7th/nvim-cmp/wiki/List-of-sources

Feat: Configure foldings

Feat: Make react snippets work on .js files too

Feat: Config dashboard
